apiVersion: v1
kind: Service
metadata:
  name: mqtt
spec:
  ports:
  - port: 1883
    targetPort: 1883
    protocol: TCP
  selector:
    name: mqtt
  type: NodePort
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
  labels:
    name: mqtt
data:
  mosquitto.conf: |    
    listener 1883
    allow_anonymous true

    log_type debug
    log_type error
    log_type warning
    log_type notice
    log_type information
    log_dest stdout
    log_timestamp_format %Y-%m-%dT%H:%M:%S

    connection_messages true
---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: mqttlogs-nfs-pv
#   labels: 
#     volume-type: nfs
# spec:
#   storageClassName: manual
#   capacity:
#     storage: 100Mi
#   accessModes:
#     - ReadWriteOnce
#   nfs:
#     server: 192.168.1.23
#     path: /mnt/DroboFS/Shares/Containers/mqtt
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: mqttlogs-nfs-pvc
# spec:
#   accessModes:
#     - ReadWriteOnce
#   storageClassName: manual
#   resources:
#     requests:
#       storage: 100Mi
#   selector: 
#     matchLabels: 
#       volume-type: nfs
# ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt
spec:
  selector:
    matchLabels:
      name: mqtt
  template:
    metadata:
      labels:
        name: mqtt
    spec:
      containers:
        - name: mqtt
          image: eclipse-mosquitto:latest
          ports:
          - containerPort: 1883
          volumeMounts:
            # - name: mqttstorage
            #   mountPath: "/mosquitto/log"
            - name: config-file
              mountPath: /mosquitto/config/mosquitto.conf
              subPath: mosquitto.conf   
      volumes:
        # - name: mqttstorage
        #   persistentVolumeClaim:
        #     claimName: mqttlogs-nfs-pvc
        - name: config-file
          configMap:
            name: mosquitto-config  






# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: mqtt 
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: mqtt
#   template:
#     metadata:
#       labels:
#         app: mqtt
#     spec:
#       containers:
#       - name: mqtt
#         image: eclipse-mosquitto:latest
#         ports:
#         - containerPort: 1883
#         volumeMounts:
#         - name: mqttstorage
#           mountPath: "/mosquitto/log"
#         - name: config-file
#           mountPath: /.config/mosquitto/mosquitto.conf
#           subPath: mosquitto.conf            
#       volumes:
#       - name: config-file
#         configMap:
#           name: mosquitto-config      
#       - name: mqttstorage
#           persistentVolumeClaim:
#             claimName: mqttlogs-nfs-pvc  